name: Android Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: grant gradlew permission
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew test

      - name: Build project
        run: ./gradlew assemble

      - name: Build and push Docker Image
        uses: mr-smithers-excellet/docker-build-push@v4
        with:
          image: frezzysmite/savingsguru
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}